# Jekyll에 오신 것을 환영합니다!
#
# 테마 소개
#
# 우아한 작성자를 위한 현대적인 플랫 스타일과 아름다운 야간/다크 모드를 
# 제공하는 또 다른 테마입니다.
#
# 웹사이트: https://github.com/jeffreytse/jekyll-theme-yat
#
# 귀하는 프로젝트나 고객을 위한 작업을 포함하여 원하는 모든 것을 할 수 있습니다.
# 단, 귀속 표시(footer나 프로젝트의 크레딧 링크)를 언급해야 합니다.
# LICENCE 파일을 참조하세요.
#
# 이 설정 파일은 블로그 전체에 영향을 미치는 설정을 위한 것이며,
# 한 번 설정하고 나면 거의 수정할 필요가 없는 값들입니다.
#
# 기술적인 이유로, 이 파일은 'bundle exec jekyll serve' 사용 시
# 자동으로 다시 로드되지 않습니다. 이 파일을 변경할 경우
# 서버 프로세스를 다시 시작해주세요.
#
# 사이트 설정
# 이것들은 새로운 사이트를 개인화하는데 사용됩니다. HTML 파일을 보면
# {{ site.title }}, {{ site.email }} 등을 통해 접근하는 것을 볼 수 있습니다.
# 원하는 사용자 정의 변수를 만들 수 있으며, {{ site.myvariable }}을 통해
# 템플릿에서 접근할 수 있습니다.

title: Paul's Archives
email: ryu.axel@gmail.com
author: Paul2021-R

# 저작권 설정
# 어떤 html 코드도 사용할 수 있으며, 현재 아래 플레이스홀더를 사용할 수 있습니다:
# * 현재 년도: {currentYear}
# * 저자: {author} (site.author와 동일한 값)
# * 저작권: (c) - ©
# * 카피레프트: (cleft)
# * 음원 저작권: (p) - ℗
#
# 예시:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"

copyright: "Copyright (cleft) 2021-{currentYear} by {author} All rights reserved."


description: >- # this means to ignore newlines until "baseurl:"
  성장하는 개발자, 소통하는 개발자, 빠른 적용을 최 우선으로 삼는 개발자. 다음을 항상 생각하며, 개발 속에서 가치를 만들어내는 것을 목표로 합니다.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paul2021-r.github.io" # the base hostname & protocol for your site, e.g. https://example.com
favicon: "/assets/images/favicon-32x32.png" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: " %Y년 %m월 %d일"

exclude:
  - temp
  - temp/**/*

# 디버그 로그를 더 보고 싶다면 true로 설정하세요
# debug: false

# 투명한 헤더를 원하지 않는다면 false로 설정하세요
# header_transparent: true

# 컨텐츠 너비를 변경하고 싶다면 다른 값으로 설정하세요
# content_width: "920px"

# Google 애널리틱스 - GA4
google_analytics: G-YDPMMYNR6Y
enableDNT: "false"

# 웹사이트 사이트맵을 생성하고 싶다면 true로 설정하세요
sitemap: true

# 사이트 언어를 변경하고 싶다면 lang 옵션을 설정하세요
lang: "ko"  # 기본 언어는 영어입니다

# 언어 번역
# 언어 참조: https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English

  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

  - lang: zh-CN
    img: https://cdn.countryflags.com/thumbs/china/flag-400.png
    text: Chinese(Simple)

  - lang: ja
    img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
    text: Japanese

  - lang: ru
    img: https://cdn.countryflags.com/thumbs/russia/flag-400.png
    text: Russian

  - lang: ko
    img: https://cdn.countryflags.com/thumbs/south-korea/flag-400.png
    text: Korean

# 테마 색상 선택
# 기본 테마 색상은 다음과 같습니다:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# 사용자 정의 색상 예시:
# theme_color: "#882250"

# 브랜드 색상 선택
# 기본 브랜드 색상은 다음과 같습니다:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
# 사용자 정의 색상 예시:
# brand_color: "#1a8e42"

# 야간/다크 모드
# 기본 모드는 "auto"이며, "auto"는 자동 야간 전환용입니다
# (19:00 - 07:00), "manual"은 수동 전환용이며,
# "on/off"는 기본 켜짐/꺼짐 설정입니다.
#
# 사용자의 선택은 사이트의 기본 설정을 우선하며
# 방문(세션) 동안 유지됩니다. 다크 모드 설정이 "manual"인 경우에만
# 모든 방문에서 항상 유지됩니다(즉, 브라우저가 닫혀도 유지됨)

# 코드 뱃지 설정
# 코드 뱃지를 활성화하거나 비활성화할 수 있습니다
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# 헤더에 특정 페이지만 링크하고 싶다면 주석을 해제하고
# 표시되어야 하는 순서대로 페이지 경로를 추가하세요
# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# 페이지 기본값
# defaults:
#   home:
#     heading: "멋진 제목"
#     subheading: "멋진 부제목"
#     banner: "이미지 URL"

# 배너 기본 설정
# 이 배너 설정은 전역 배너 기본값이지만,
# front matter를 통해 특정 게시물에 대해 구성할 수도 있습니다
banner:
  # video: https://cdn.pixabay.com/video/2015/12/11/1656-148614494_medium.mp4         # Video banner source
  # loop: true              # Video loop
  # volume: 0               # Video volume (100% is 1.0)
  # muted: true
  # start_at: 0             # Video start time
  image: https://cdn.pixabay.com/photo/2015/05/26/23/52/technology-785742_1280.jpg            # Image banner source
  opacity: 0.618
  background: "#000"
  height: "70vh"
  heading_style: "font-size: 4.25em; font-weight: bold; text-decoration: underline"
  subheading_style: "color: gold" # Custom subheading style (e.g. color: gold)

# exceprt 설정
excerpt:
  default_image: /assets/images/default-image.png  # Default image when the image style is not none
  image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
  image_width: 38.2%      # Image default width
  image_height: 160px     # Image default height
  text_size: 350          # Words default size

# 페이지네이션 설정
show_excerpts: true     # 요약 텍스트 보여주기
paginate: 5             # 한 페이지에 보여줄 포스트 수
paginate_path: "/page:num/"

# Photo previewer settings (PhotoSwipe 5)
# the options please refer to: https://photoswipe.com/options/
# photo_previewer:
#  gallery: "section.main"
#  children: "a.photo-swipe"
#  bgOpacity: 0.8
#  padding:
#    top: 20
#    bottom: 40
#    left: 100
#    right: 100


# Disqus 댓글
# disqus:
#   shortname: "Disqus 사용자명"

# Gitment 댓글
# gitment:
#   username: "GitHub 사용자명"
#   repo: "댓글을 저장할 저장소"
#   client_id: "클라이언트 ID"
#   client_secret: "클라이언트 시크릿"
#   redirect_uri: "리다이렉트 URL"   # 사용자 정의 도메인을 사용하는 경우

# Utterances 댓글
# https://utteranc.es/ 참조
# utterances의 테마가 사이트 테마를 따르게 하려면 follow_site_theme을 true로 설정

utterances:
  repo: "Paul2021-R/blog-comments"
  issue_term: "blog-comment:"
  label: "utterances"
  theme: "github-light"
  follow_site_theme: true

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
